name: Trigger CodeBuild on Push

on:
  push:
    branches:
      - main  # 触发构建的分支，可以是 main 或者其他你选择的分支

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境来运行任务

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出当前的 GitHub 仓库代码

      - name: Trigger AWS CodeBuild
        uses: aws-actions/aws-codebuild-trigger-action@v1  # 使用 AWS CodeBuild GitHub Action
        with:
          project-name: my-codebuild-project  # 这里替换为你在 AWS 中创建的 CodeBuild 项目名称
          region: 'ap-northeast-1'  # AWS 区域，例如东京区域

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # 从 GitHub Secrets 中获取 AWS 访问密钥
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # 从 GitHub Secrets 中获取 AWS 密钥
          AWS_REGION: 'ap-northeast-1'  # 你选择的 AWS 区域
